apiVersion: v1
kind: Service
metadata:
  name: ws-service
  labels:
    app: ws
spec:
  ports:
    - port: 80
  selector:
    app: ws
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ws
spec:
  selector:
    matchLabels:
      app: ws
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
      - image: 159.31.200.29:5000/amc/ws-rest:v1
        name: ws-rest
        ports:
        - containerPort: 5000
      - image: 159.31.200.29:5000/amc/ws-frontend:v1
        name: ws-frontend
        ports:
        - containerPort: 3000
      - image: jboss/keycloak
        name: ws-keycloak
        ports:
        - containerPort: 8080