version: '3.7'
services: 

  ws-frontend:
    image: 159.31.200.29:5000/amc/ws-frontend:v1
    container_name: frontend
    restart: always
    build: ../ws-frontend
    environment:
    - BACKEND_HOST=localhost
    - BACKEND_PORT=5000
    - KEYCLOAK_HOST=localhost
    - KEYCLOAK_PORT=8080

  ws-rest:
    container_name: ws-rest
    build: ../ws-rest
    image: 159.31.200.29:5000/amc/ws-rest:v1
    environment:
    - KEYCLOAK_HOST=localhost
    - KEYCLOAK_PORT=8080
    restart: always

  ws-keycloak:
    container_name: ws-keycloak
    image: jboss/keycloak
    volumes: 
      - ./realm-export.json:/tmp/realm-export.json
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    restart: always